"""
QuizSummary model for the learning system.

Represents the post-quiz summary generated by the LLM after a quiz session completes.
"""

from datetime import datetime
from sqlalchemy import Column, Integer, DateTime, ForeignKey, JSON, Index, String
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class QuizSummary(Base):
    """
    QuizSummary model for storing post-quiz evaluations.

    Contains the LLM-generated summary after a quiz session completes,
    including which concepts were mastered and which need improvement.

    Attributes:
        summary_id: Primary key, auto-incrementing integer
        session_id: Foreign key to quiz_sessions table (one-to-one relationship)
        user_course_id: Foreign key to user_courses table
        concepts_mastered: JSON array of concept names the user mastered
                          Format: ["concept1", "concept2", ...]
        concepts_weak: JSON array of weak concepts with explanations
                      Format: [
                        {
                          "concept": "concept_name",
                          "user_answer": "what user said",
                          "correct_explanation": "what's correct"
                        },
                        ...
                      ]
        created_at: When summary was generated (UTC)

    Relationships:
        quiz_session: Reference to the QuizSession (one-to-one)
        user_course: Reference to the UserCourse for tracking progress

    Note:
        - One summary per quiz session
        - concepts_mastered and concepts_weak are JSON arrays/objects
        - Summary is generated automatically by LLM after quiz completion
    """

    __tablename__ = "quiz_summaries"

    summary_id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(Integer, ForeignKey("quiz_sessions.session_id", ondelete="CASCADE"), nullable=False, unique=True)
    user_course_id = Column(Integer, ForeignKey("user_courses.user_course_id", ondelete="SET NULL"), nullable=True)
    concepts_mastered = Column(JSON, nullable=True)  # JSON array of mastered concept names
    concepts_weak = Column(JSON, nullable=True)  # JSON array with concept, user_answer, correct_explanation
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    next_review_at = Column(DateTime, nullable=True)  # When to send spaced repetition reminder
    review_count = Column(Integer, default=0, nullable=False, server_default="0")  # How many reviews done

    # Relationships
    quiz_session = relationship(
        "QuizSession",
        back_populates="quiz_summary",
        lazy="select"
    )
    user_course = relationship(
        "UserCourse",
        back_populates="quiz_summaries",
        lazy="select"
    )

    # Indexes
    __table_args__ = (
        Index("idx_quiz_summary_session_id", "session_id"),
        Index("idx_quiz_summary_user_course_id", "user_course_id"),
        Index("idx_quiz_summary_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<QuizSummary(summary_id={self.summary_id}, session_id={self.session_id}, user_course_id={self.user_course_id})>"
