"""initial schema

Revision ID: 22d1932ee4e1
Revises: 
Create Date: 2026-03-24 17:25:38.128753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d1932ee4e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index('idx_source_source_id', 'courses', ['source', 'source_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('lessons',
    sa.Column('lesson_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_index('idx_lesson_course_id', 'lessons', ['course_id'], unique=False)
    op.create_index('idx_lesson_sequence', 'lessons', ['course_id', 'sequence_number'], unique=False)
    op.create_table('onboarding_states',
    sa.Column('onboarding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('q1_answer', sa.String(length=50), nullable=True),
    sa.Column('q2_answer', sa.String(length=50), nullable=True),
    sa.Column('assessed_level', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('hours_per_day', sa.Integer(), nullable=True),
    sa.Column('reminder_time', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('onboarding_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_onboarding_current_step', 'onboarding_states', ['current_step'], unique=False)
    op.create_index('idx_onboarding_user_id', 'onboarding_states', ['user_id'], unique=False)
    op.create_table('user_courses',
    sa.Column('user_course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_course_id')
    )
    op.create_index('idx_user_course_course_id', 'user_courses', ['course_id'], unique=False)
    op.create_index('idx_user_course_status', 'user_courses', ['status'], unique=False)
    op.create_index('idx_user_course_user_id', 'user_courses', ['user_id'], unique=False)
    op.create_table('concepts',
    sa.Column('concept_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id')
    )
    op.create_index('idx_concept_lesson_id', 'concepts', ['lesson_id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_quiz_session_lesson_id', 'quiz_sessions', ['lesson_id'], unique=False)
    op.create_index('idx_quiz_session_started_at', 'quiz_sessions', ['started_at'], unique=False)
    op.create_index('idx_quiz_session_status', 'quiz_sessions', ['status'], unique=False)
    op.create_index('idx_quiz_session_user_id', 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('engagement_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.concept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index('idx_quiz_answer_concept_id', 'quiz_answers', ['concept_id'], unique=False)
    op.create_index('idx_quiz_answer_is_correct', 'quiz_answers', ['is_correct'], unique=False)
    op.create_index('idx_quiz_answer_session_id', 'quiz_answers', ['session_id'], unique=False)
    op.create_table('quiz_summaries',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_course_id', sa.Integer(), nullable=True),
    sa.Column('concepts_mastered', sa.JSON(), nullable=True),
    sa.Column('concepts_weak', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_course_id'], ['user_courses.user_course_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_quiz_summary_created_at', 'quiz_summaries', ['created_at'], unique=False)
    op.create_index('idx_quiz_summary_session_id', 'quiz_summaries', ['session_id'], unique=False)
    op.create_index('idx_quiz_summary_user_course_id', 'quiz_summaries', ['user_course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_quiz_summary_user_course_id', table_name='quiz_summaries')
    op.drop_index('idx_quiz_summary_session_id', table_name='quiz_summaries')
    op.drop_index('idx_quiz_summary_created_at', table_name='quiz_summaries')
    op.drop_table('quiz_summaries')
    op.drop_index('idx_quiz_answer_session_id', table_name='quiz_answers')
    op.drop_index('idx_quiz_answer_is_correct', table_name='quiz_answers')
    op.drop_index('idx_quiz_answer_concept_id', table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index('idx_quiz_session_user_id', table_name='quiz_sessions')
    op.drop_index('idx_quiz_session_status', table_name='quiz_sessions')
    op.drop_index('idx_quiz_session_started_at', table_name='quiz_sessions')
    op.drop_index('idx_quiz_session_lesson_id', table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index('idx_concept_lesson_id', table_name='concepts')
    op.drop_table('concepts')
    op.drop_index('idx_user_course_user_id', table_name='user_courses')
    op.drop_index('idx_user_course_status', table_name='user_courses')
    op.drop_index('idx_user_course_course_id', table_name='user_courses')
    op.drop_table('user_courses')
    op.drop_index('idx_onboarding_user_id', table_name='onboarding_states')
    op.drop_index('idx_onboarding_current_step', table_name='onboarding_states')
    op.drop_table('onboarding_states')
    op.drop_index('idx_lesson_sequence', table_name='lessons')
    op.drop_index('idx_lesson_course_id', table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_source_source_id', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
