"""add_content_markdown_to_lessons

Revision ID: 5b2f0cc77e7a
Revises: 09fcb00f5b30
Create Date: 2026-04-23 10:33:18.239059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2f0cc77e7a'
down_revision: Union[str, Sequence[str], None] = '09fcb00f5b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('content_markdown', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('content_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'content_generated_at')
    op.drop_column('lessons', 'content_markdown')
    # ### end Alembic commands ###
