"""add_last_activity_at_to_user_courses

Revision ID: 74d83fa0bdb7
Revises: 42d4167ad3c4
Create Date: 2026-04-21 13:59:41.697055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d83fa0bdb7'
down_revision: Union[str, Sequence[str], None] = '42d4167ad3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_courses', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_courses', 'last_activity_at')
    # ### end Alembic commands ###
