"""make quiz_answer concept_id nullable

Revision ID: 87d575cf97ab
Revises: fa6c6359d5d0
Create Date: 2026-03-28 17:01:38.869501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87d575cf97ab'
down_revision: Union[str, Sequence[str], None] = 'fa6c6359d5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'concept_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('quiz_answers_ibfk_1'), 'quiz_answers', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_answers', 'concepts', ['concept_id'], ['concept_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_answers', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_answers_ibfk_1'), 'quiz_answers', 'concepts', ['concept_id'], ['concept_id'], ondelete='CASCADE')
    op.alter_column('quiz_answers', 'concept_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
