"""add_reminder_time_to_users

Revision ID: a48efb32b68d
Revises: b06c0b572bbe
Create Date: 2026-04-21 00:01:30.722411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48efb32b68d'
down_revision: Union[str, Sequence[str], None] = 'b06c0b572bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reminder_time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminder_time')
    # ### end Alembic commands ###
