"""add_course_topic_to_onboarding_state

Revision ID: fa6c6359d5d0
Revises: 87cbb2432c2d
Create Date: 2026-03-26 00:50:40.566517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6c6359d5d0'
down_revision: Union[str, Sequence[str], None] = '87cbb2432c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_states', sa.Column('course_topic', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_states', 'course_topic')
    # ### end Alembic commands ###
